name: CI

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: brew install speedtest-cli
      - run: speedtest
