name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: create dir
        run: mkdir ~/releases
      - name: touch file
        run: echo Hello >> ~/releases/hi.txt
      - uses: actions/upload-artifact@v2
        with:
          name: Maven
          path: ~/releases

