name: CI

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: shasum -a 256 README.md
        if: env.PUBLISH_STABLE == 'true'
        env:
          PUBLISH_STABLE: ${{ secrets.PUBLISH_STABLE }}
