name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
