name: CI

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java-version: [8, 9, 10, 11, 12, 13]
        package: [jre, jdk]
        os: [ubuntu-latest]
        # os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-latest, windows-2016, windows-2019]
        
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }} # The JDK version to make available on the path.
          java-package: ${{ matrix.package }} # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
