name: Autocloser

on: [pull_request]

jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
    - name: Autoclose pull requests that do not provide information
      uses: roots/issue-closer@v1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-close-message: "@${pull_request.user.login} this pull request was automatically closed because it looks like you meant to open it elsewhere."
        pr-pattern: "^((?!Before issuing a pull request, please see the contributing page).)*$"