name: format-command

on:
  repository_dispatch:
    types: [format-command]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      # Checkout the pull request branch
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      # Append a response to the user that issued the command
      - name: Append to README.md
        run: echo "Hello @${{ github.event.client_payload.github.actor }}!" >> hello-world.txt

      - name: Create Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Run wpiformat"
          commit_user_name: GitHub
          commit_user_email: noreply@github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: '+1'